"""empty message

Revision ID: 194e839903bc
Revises: 4c142f7b5eda
Create Date: 2019-11-24 04:49:20.493686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194e839903bc'
down_revision = '4c142f7b5eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('surname', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'surname')
    # ### end Alembic commands ###
